//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orc.Theming.Example.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orc.Theming.Example.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string AgeWizardPageView_Age {
            get {
                return ResourceManager.GetString("AgeWizardPageView_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string ButtonView_Disabled {
            get {
                return ResourceManager.GetString("ButtonView_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test menu item 1.
        /// </summary>
        internal static string ButtonView_TestMenuItem1 {
            get {
                return ResourceManager.GetString("ButtonView_TestMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test_1.
        /// </summary>
        internal static string ButtonView_TestMenuItem1_Sub1 {
            get {
                return ResourceManager.GetString("ButtonView_TestMenuItem1_Sub1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test_2.
        /// </summary>
        internal static string ButtonView_TestMenuItem1_Sub2 {
            get {
                return ResourceManager.GetString("ButtonView_TestMenuItem1_Sub2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test_3.
        /// </summary>
        internal static string ButtonView_TestMenuItem1_Sub3 {
            get {
                return ResourceManager.GetString("ButtonView_TestMenuItem1_Sub3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test menu item 2.
        /// </summary>
        internal static string ButtonView_TestMenuItem2 {
            get {
                return ResourceManager.GetString("ButtonView_TestMenuItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test menu item 3.
        /// </summary>
        internal static string ButtonView_TestMenuItem3 {
            get {
                return ResourceManager.GetString("ButtonView_TestMenuItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked &amp; disabled state.
        /// </summary>
        internal static string CheckBoxView_CheckedDisabledState {
            get {
                return ResourceManager.GetString("CheckBoxView_CheckedDisabledState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked state.
        /// </summary>
        internal static string CheckBoxView_CheckedState {
            get {
                return ResourceManager.GetString("CheckBoxView_CheckedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three state.
        /// </summary>
        internal static string CheckBoxView_ThreeState {
            get {
                return ResourceManager.GetString("CheckBoxView_ThreeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unchecked &amp; disabled state.
        /// </summary>
        internal static string CheckBoxView_UncheckedDisabledState {
            get {
                return ResourceManager.GetString("CheckBoxView_UncheckedDisabledState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unchecked state.
        /// </summary>
        internal static string CheckBoxView_UncheckedState {
            get {
                return ResourceManager.GetString("CheckBoxView_UncheckedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel via code.
        /// </summary>
        internal static string ComponentsWizardPageView_CancelViaCode {
            get {
                return ResourceManager.GetString("ComponentsWizardPageView_CancelViaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the components you want to use:.
        /// </summary>
        internal static string ComponentsWizardPageView_Description {
            get {
                return ResourceManager.GetString("ComponentsWizardPageView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move back via code.
        /// </summary>
        internal static string ComponentsWizardPageView_MoveBackViaCode {
            get {
                return ResourceManager.GetString("ComponentsWizardPageView_MoveBackViaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move forward via code.
        /// </summary>
        internal static string ComponentsWizardPageView_MoveForwardViaCode {
            get {
                return ResourceManager.GetString("ComponentsWizardPageView_MoveForwardViaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move next or finish via code.
        /// </summary>
        internal static string ComponentsWizardPageView_MoveNextOrFinishViaCode {
            get {
                return ResourceManager.GetString("ComponentsWizardPageView_MoveNextOrFinishViaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        internal static string ComponentsWizardPageView_SelectAll {
            get {
                return ResourceManager.GetString("ComponentsWizardPageView_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combobox.
        /// </summary>
        internal static string ControlPaddingsView_Combobox {
            get {
                return ResourceManager.GetString("ControlPaddingsView_Combobox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilterBox.
        /// </summary>
        internal static string ControlPaddingsView_FilterBox {
            get {
                return ResourceManager.GetString("ControlPaddingsView_FilterBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBox.
        /// </summary>
        internal static string ControlPaddingsView_TextBox {
            get {
                return ResourceManager.GetString("ControlPaddingsView_TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WatermarkTextBox.
        /// </summary>
        internal static string ControlPaddingsView_WatermarkTextBox {
            get {
                return ResourceManager.GetString("ControlPaddingsView_WatermarkTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button.
        /// </summary>
        internal static string ControlsView_Button {
            get {
                return ResourceManager.GetString("ControlsView_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button with Square behavior.
        /// </summary>
        internal static string ControlsView_ButtonWithSquareBehavior {
            get {
                return ResourceManager.GetString("ControlsView_ButtonWithSquareBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBox.
        /// </summary>
        internal static string ControlsView_CheckBox {
            get {
                return ResourceManager.GetString("ControlsView_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComboBox.
        /// </summary>
        internal static string ControlsView_ComboBox {
            get {
                return ResourceManager.GetString("ControlsView_ComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This view shows all the controls with the alignments updated with the style forwarders. The first row contains an alignment helper border. All styles must also respect the current theme color..
        /// </summary>
        internal static string ControlsView_Description {
            get {
                return ResourceManager.GetString("ControlsView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable alignment grid.
        /// </summary>
        internal static string ControlsView_EnableAlignmentGrid {
            get {
                return ResourceManager.GetString("ControlsView_EnableAlignmentGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter box.
        /// </summary>
        internal static string ControlsView_FilterBoxText {
            get {
                return ResourceManager.GetString("ControlsView_FilterBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GridSplitter.
        /// </summary>
        internal static string ControlsView_GridSplitter {
            get {
                return ResourceManager.GetString("ControlsView_GridSplitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupBox.
        /// </summary>
        internal static string ControlsView_GroupBox {
            get {
                return ResourceManager.GetString("ControlsView_GroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 1.
        /// </summary>
        internal static string ControlsView_Item1 {
            get {
                return ResourceManager.GetString("ControlsView_Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 11.
        /// </summary>
        internal static string ControlsView_Item11 {
            get {
                return ResourceManager.GetString("ControlsView_Item11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 2.
        /// </summary>
        internal static string ControlsView_Item2 {
            get {
                return ResourceManager.GetString("ControlsView_Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 21.
        /// </summary>
        internal static string ControlsView_Item21 {
            get {
                return ResourceManager.GetString("ControlsView_Item21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 3.
        /// </summary>
        internal static string ControlsView_Item3 {
            get {
                return ResourceManager.GetString("ControlsView_Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 31.
        /// </summary>
        internal static string ControlsView_Item31 {
            get {
                return ResourceManager.GetString("ControlsView_Item31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 4.
        /// </summary>
        internal static string ControlsView_Item4 {
            get {
                return ResourceManager.GetString("ControlsView_Item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item 41.
        /// </summary>
        internal static string ControlsView_Item41 {
            get {
                return ResourceManager.GetString("ControlsView_Item41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        internal static string ControlsView_Label {
            get {
                return ResourceManager.GetString("ControlsView_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkLabel.
        /// </summary>
        internal static string ControlsView_LinkLabel {
            get {
                return ResourceManager.GetString("ControlsView_LinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListBox.
        /// </summary>
        internal static string ControlsView_ListBox {
            get {
                return ResourceManager.GetString("ControlsView_ListBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListView.
        /// </summary>
        internal static string ControlsView_ListView {
            get {
                return ResourceManager.GetString("ControlsView_ListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-line controls.
        /// </summary>
        internal static string ControlsView_MultiLineControls {
            get {
                return ResourceManager.GetString("ControlsView_MultiLineControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this is a multiline textbox.
        /// </summary>
        internal static string ControlsView_MultilineTextBox {
            get {
                return ResourceManager.GetString("ControlsView_MultilineTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orc controls.
        /// </summary>
        internal static string ControlsView_OrcControls {
            get {
                return ResourceManager.GetString("ControlsView_OrcControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orc.Controls: DateTimePicker.
        /// </summary>
        internal static string ControlsView_OrcControls_DateTimePicker {
            get {
                return ResourceManager.GetString("ControlsView_OrcControls_DateTimePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orc.Controls: DropDownButton.
        /// </summary>
        internal static string ControlsView_OrcControls_DropDownButton {
            get {
                return ResourceManager.GetString("ControlsView_OrcControls_DropDownButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orc.Controls: FilterBox.
        /// </summary>
        internal static string ControlsView_OrcControls_FilterBox {
            get {
                return ResourceManager.GetString("ControlsView_OrcControls_FilterBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orc.Controls: LinkLabel.
        /// </summary>
        internal static string ControlsView_OrcControls_LinkLabel {
            get {
                return ResourceManager.GetString("ControlsView_OrcControls_LinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orc.Controls: NumericTextBox.
        /// </summary>
        internal static string ControlsView_OrcControls_NumericTextBox {
            get {
                return ResourceManager.GetString("ControlsView_OrcControls_NumericTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orc.Controls: RangeSlider.
        /// </summary>
        internal static string ControlsView_OrcControls_RangeSlider {
            get {
                return ResourceManager.GetString("ControlsView_OrcControls_RangeSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orc.Controls: TimeSpanPicker.
        /// </summary>
        internal static string ControlsView_OrcControls_TimeSpanPicker {
            get {
                return ResourceManager.GetString("ControlsView_OrcControls_TimeSpanPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orc.Controls: WatermarkTextBox.
        /// </summary>
        internal static string ControlsView_OrcControls_WatermarkTextBox {
            get {
                return ResourceManager.GetString("ControlsView_OrcControls_WatermarkTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orc.Controls controls.
        /// </summary>
        internal static string ControlsView_OrcControlsControls {
            get {
                return ResourceManager.GetString("ControlsView_OrcControlsControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orchestra: BusyIndicator.
        /// </summary>
        internal static string ControlsView_Orchestra_BusyIndicator {
            get {
                return ResourceManager.GetString("ControlsView_Orchestra_BusyIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orchestra: FluidProgressBar.
        /// </summary>
        internal static string ControlsView_Orchestra_FluidProgressBar {
            get {
                return ResourceManager.GetString("ControlsView_Orchestra_FluidProgressBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other controls.
        /// </summary>
        internal static string ControlsView_OtherControls {
            get {
                return ResourceManager.GetString("ControlsView_OtherControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordBox.
        /// </summary>
        internal static string ControlsView_PasswordBox {
            get {
                return ResourceManager.GetString("ControlsView_PasswordBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProgressBar.
        /// </summary>
        internal static string ControlsView_ProgressBar {
            get {
                return ResourceManager.GetString("ControlsView_ProgressBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RadioButton.
        /// </summary>
        internal static string ControlsView_RadioButton {
            get {
                return ResourceManager.GetString("ControlsView_RadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RepeatButton.
        /// </summary>
        internal static string ControlsView_RepeatButton {
            get {
                return ResourceManager.GetString("ControlsView_RepeatButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RichTextBox.
        /// </summary>
        internal static string ControlsView_RichTextBox {
            get {
                return ResourceManager.GetString("ControlsView_RichTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider.
        /// </summary>
        internal static string ControlsView_Slider {
            get {
                return ResourceManager.GetString("ControlsView_Slider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBlock.
        /// </summary>
        internal static string ControlsView_TextBlock {
            get {
                return ResourceManager.GetString("ControlsView_TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBox.
        /// </summary>
        internal static string ControlsView_TextBox {
            get {
                return ResourceManager.GetString("ControlsView_TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBox for alignment.
        /// </summary>
        internal static string ControlsView_TextBoxForAlignment {
            get {
                return ResourceManager.GetString("ControlsView_TextBoxForAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textbox should be similar to ComboBox.
        /// </summary>
        internal static string ControlsView_TextboxSimilarToComboBox {
            get {
                return ResourceManager.GetString("ControlsView_TextboxSimilarToComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textbox should be similar to PasswordBox.
        /// </summary>
        internal static string ControlsView_TextboxSimilarToPasswordBox {
            get {
                return ResourceManager.GetString("ControlsView_TextboxSimilarToPasswordBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToggleButton.
        /// </summary>
        internal static string ControlsView_ToggleButton {
            get {
                return ResourceManager.GetString("ControlsView_ToggleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TreeView.
        /// </summary>
        internal static string ControlsView_TreeView {
            get {
                return ResourceManager.GetString("ControlsView_TreeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a watermark.
        /// </summary>
        internal static string ControlsView_Watermark {
            get {
                return ResourceManager.GetString("ControlsView_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPF controls.
        /// </summary>
        internal static string ControlsView_WpfControls {
            get {
                return ResourceManager.GetString("ControlsView_WpfControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPF controls (sizes).
        /// </summary>
        internal static string ControlsView_WpfControlsSizes {
            get {
                return ResourceManager.GetString("ControlsView_WpfControlsSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move pointer here....
        /// </summary>
        internal static string FontImageCursorView_MovePointerHere {
            get {
                return ResourceManager.GetString("FontImageCursorView_MovePointerHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute.
        /// </summary>
        internal static string FontSizeView_Absolute {
            get {
                return ResourceManager.GetString("FontSizeView_Absolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is 10.
        /// </summary>
        internal static string FontSizeView_Absolute_10 {
            get {
                return ResourceManager.GetString("FontSizeView_Absolute_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is 12.
        /// </summary>
        internal static string FontSizeView_Absolute_12 {
            get {
                return ResourceManager.GetString("FontSizeView_Absolute_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is 14.
        /// </summary>
        internal static string FontSizeView_Absolute_14 {
            get {
                return ResourceManager.GetString("FontSizeView_Absolute_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is 16.
        /// </summary>
        internal static string FontSizeView_Absolute_16 {
            get {
                return ResourceManager.GetString("FontSizeView_Absolute_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is 18.
        /// </summary>
        internal static string FontSizeView_Absolute_18 {
            get {
                return ResourceManager.GetString("FontSizeView_Absolute_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default font size.
        /// </summary>
        internal static string FontSizeView_DefaultFontSize {
            get {
                return ResourceManager.GetString("FontSizeView_DefaultFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta.
        /// </summary>
        internal static string FontSizeView_Delta {
            get {
                return ResourceManager.GetString("FontSizeView_Delta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is 0.
        /// </summary>
        internal static string FontSizeView_Delta_0 {
            get {
                return ResourceManager.GetString("FontSizeView_Delta_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is -2.
        /// </summary>
        internal static string FontSizeView_Delta_Minus2 {
            get {
                return ResourceManager.GetString("FontSizeView_Delta_Minus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is -4.
        /// </summary>
        internal static string FontSizeView_Delta_Minus4 {
            get {
                return ResourceManager.GetString("FontSizeView_Delta_Minus4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is +2.
        /// </summary>
        internal static string FontSizeView_Delta_Plus2 {
            get {
                return ResourceManager.GetString("FontSizeView_Delta_Plus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is +4.
        /// </summary>
        internal static string FontSizeView_Delta_Plus4 {
            get {
                return ResourceManager.GetString("FontSizeView_Delta_Plus4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No subscriptions (not responsive).
        /// </summary>
        internal static string FontSizeView_NoSubscriptions {
            get {
                return ResourceManager.GetString("FontSizeView_NoSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is 0.6.
        /// </summary>
        internal static string FontSizeView_Scale_0_6 {
            get {
                return ResourceManager.GetString("FontSizeView_Scale_0_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is 0.8.
        /// </summary>
        internal static string FontSizeView_Scale_0_8 {
            get {
                return ResourceManager.GetString("FontSizeView_Scale_0_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is 1.0.
        /// </summary>
        internal static string FontSizeView_Scale_1_0 {
            get {
                return ResourceManager.GetString("FontSizeView_Scale_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is 1.2.
        /// </summary>
        internal static string FontSizeView_Scale_1_2 {
            get {
                return ResourceManager.GetString("FontSizeView_Scale_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is 1.4.
        /// </summary>
        internal static string FontSizeView_Scale_1_4 {
            get {
                return ResourceManager.GetString("FontSizeView_Scale_1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaling.
        /// </summary>
        internal static string FontSizeView_Scaling {
            get {
                return ResourceManager.GetString("FontSizeView_Scaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions (responsive).
        /// </summary>
        internal static string FontSizeView_Subscriptions {
            get {
                return ResourceManager.GetString("FontSizeView_Subscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text.
        /// </summary>
        internal static string ListBoxView_Text {
            get {
                return ResourceManager.GetString("ListBoxView_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string ListViewView_Enabled {
            get {
                return ResourceManager.GetString("ListViewView_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here goes your real content.
        /// </summary>
        internal static string MenuView_RealContent {
            get {
                return ResourceManager.GetString("MenuView_RealContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This wizard page shows you how to map textbox elements to a model and validate them. Notice that you cannot move to the next page while the fields are not yet valid. When navigating forward and back, you will see the values are automatically restored.
        ///
        ///The cool thing is that the view model for this page only has 28 (!) lines of code. This means your pages stay small and are easily maintainable..
        /// </summary>
        internal static string PersonWizardPageView_Description {
            get {
                return ResourceManager.GetString("PersonWizardPageView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string PersonWizardPageView_FirstName {
            get {
                return ResourceManager.GetString("PersonWizardPageView_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string PersonWizardPageView_LastName {
            get {
                return ResourceManager.GetString("PersonWizardPageView_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular bar 1.
        /// </summary>
        internal static string ProgressBarView_CircularBar1 {
            get {
                return ResourceManager.GetString("ProgressBarView_CircularBar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular bar 2.
        /// </summary>
        internal static string ProgressBarView_CircularBar2 {
            get {
                return ResourceManager.GetString("ProgressBarView_CircularBar2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular bar 3.
        /// </summary>
        internal static string ProgressBarView_CircularBar3 {
            get {
                return ResourceManager.GetString("ProgressBarView_CircularBar3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular progress bars.
        /// </summary>
        internal static string ProgressBarView_CircularProgressBars {
            get {
                return ResourceManager.GetString("ProgressBarView_CircularProgressBars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled | Determinate.
        /// </summary>
        internal static string ProgressBarView_DisabledDeterminate {
            get {
                return ResourceManager.GetString("ProgressBarView_DisabledDeterminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled | Indeterminate.
        /// </summary>
        internal static string ProgressBarView_DisabledIndeterminate {
            get {
                return ResourceManager.GetString("ProgressBarView_DisabledIndeterminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled | Determinate.
        /// </summary>
        internal static string ProgressBarView_EnabledDeterminate {
            get {
                return ResourceManager.GetString("ProgressBarView_EnabledDeterminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled | Indeterminate.
        /// </summary>
        internal static string ProgressBarView_EnabledIndeterminate {
            get {
                return ResourceManager.GetString("ProgressBarView_EnabledIndeterminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked &amp; disabled state.
        /// </summary>
        internal static string RadioButtonView_CheckedDisabledState {
            get {
                return ResourceManager.GetString("RadioButtonView_CheckedDisabledState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked state.
        /// </summary>
        internal static string RadioButtonView_CheckedState {
            get {
                return ResourceManager.GetString("RadioButtonView_CheckedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unchecked &amp; disabled state.
        /// </summary>
        internal static string RadioButtonView_UncheckedDisabledState {
            get {
                return ResourceManager.GetString("RadioButtonView_UncheckedDisabledState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unchecked state.
        /// </summary>
        internal static string RadioButtonView_UncheckedState {
            get {
                return ResourceManager.GetString("RadioButtonView_UncheckedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string RepeatButtonView_Default {
            get {
                return ResourceManager.GetString("RepeatButtonView_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string RepeatButtonView_Disabled {
            get {
                return ResourceManager.GetString("RepeatButtonView_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsSelected.
        /// </summary>
        internal static string SeparateWindow_IsSelected {
            get {
                return ResourceManager.GetString("SeparateWindow_IsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string SeparateWindow_Name {
            get {
                return ResourceManager.GetString("SeparateWindow_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your skills:.
        /// </summary>
        internal static string SkillsWizardPageView_Description {
            get {
                return ResourceManager.GetString("SkillsWizardPageView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        internal static string SkillsWizardPageView_SelectAll {
            get {
                return ResourceManager.GetString("SkillsWizardPageView_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here goes your real content.
        /// </summary>
        internal static string TabControlView_RealContent {
            get {
                return ResourceManager.GetString("TabControlView_RealContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default state.
        /// </summary>
        internal static string TextBoxView_DefaultState {
            get {
                return ResourceManager.GetString("TextBoxView_DefaultState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string TextBoxView_Disabled {
            get {
                return ResourceManager.GetString("TextBoxView_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focused state + text selection.
        /// </summary>
        internal static string TextBoxView_FocusedStateTextSelection {
            get {
                return ResourceManager.GetString("TextBoxView_FocusedStateTextSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Stretch.
        /// </summary>
        internal static string TextBoxView_HorizontalStretch {
            get {
                return ResourceManager.GetString("TextBoxView_HorizontalStretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive text selection.
        /// </summary>
        internal static string TextBoxView_InactiveTextSelection {
            get {
                return ResourceManager.GetString("TextBoxView_InactiveTextSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Stretch and multiline.
        /// </summary>
        internal static string TextBoxView_VerticalStretchAndMultiline {
            get {
                return ResourceManager.GetString("TextBoxView_VerticalStretchAndMultiline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image with auto replacement.
        /// </summary>
        internal static string ThemeImageView_ImageWithAutoReplacement {
            get {
                return ResourceManager.GetString("ThemeImageView_ImageWithAutoReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image with placeholder.
        /// </summary>
        internal static string ThemeImageView_ImageWithPlaceholder {
            get {
                return ResourceManager.GetString("ThemeImageView_ImageWithPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare all.
        /// </summary>
        internal static string ToggleButtonView_CompareAll {
            get {
                return ResourceManager.GetString("ToggleButtonView_CompareAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string ToggleButtonView_Default {
            get {
                return ResourceManager.GetString("ToggleButtonView_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string ToggleButtonView_Disabled {
            get {
                return ResourceManager.GetString("ToggleButtonView_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressed.
        /// </summary>
        internal static string ToggleButtonView_Pressed {
            get {
                return ResourceManager.GetString("ToggleButtonView_Pressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string ToolBarView_Copy {
            get {
                return ResourceManager.GetString("ToolBarView_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string ToolBarView_Cut {
            get {
                return ResourceManager.GetString("ToolBarView_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string ToolBarView_New {
            get {
                return ResourceManager.GetString("ToolBarView_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string ToolBarView_Open {
            get {
                return ResourceManager.GetString("ToolBarView_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string ToolBarView_Paste {
            get {
                return ResourceManager.GetString("ToolBarView_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ToolBarView_Save {
            get {
                return ResourceManager.GetString("ToolBarView_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show separate window....
        /// </summary>
        internal static string WizardView_ShowSeparateWindow {
            get {
                return ResourceManager.GetString("WizardView_ShowSeparateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show wizard....
        /// </summary>
        internal static string WizardView_ShowWizard {
            get {
                return ResourceManager.GetString("WizardView_ShowWizard", resourceCulture);
            }
        }
    }
}
